# Generated by Django 4.1 on 2022-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_crop_delivery_type_crop_discount_crop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='delivery_type',
            field=models.CharField(choices=[('farm-to-door', 'Farm to door'), ('pickup', 'Pick Up')], max_length=300),
        ),
        migrations.AlterField(
            model_name='crop',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
