# Generated by Django 4.1 on 2022-08-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_alter_crop_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='delivery_type',
        ),
    ]
