# Generated by Django 4.1 on 2022-08-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_rename_farmer_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetail',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farmer.farm'),
        ),
    ]
