# Generated by Django 4.1 on 2022-08-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmerdetail_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetail',
            name='farm_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farmer.farm'),
        ),
    ]
