# Generated by Django 4.1 on 2022-08-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_rename_farmer_firstname_farmerdetail_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdetail',
            old_name='description',
            new_name='about',
        ),
    ]
